// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanPK;

#nullable disable

namespace PlanPK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanPK.Issues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("FaktHours")
                        .HasColumnType("float");

                    b.Property<string>("IssuesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PlanHours")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TermDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IssuesId");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("PlanPK.Issues", b =>
                {
                    b.HasOne("PlanPK.Issues", null)
                        .WithMany("ChildrenIssue")
                        .HasForeignKey("IssuesId");
                });

            modelBuilder.Entity("PlanPK.Issues", b =>
                {
                    b.Navigation("ChildrenIssue");
                });
#pragma warning restore 612, 618
        }
    }
}
